define(["Tone/core/Tone"],function(Tone){"use strict";Tone.CtrlPattern=function(){var options=this.optionsObject(arguments,["values","type"],Tone.CtrlPattern.defaults);this.values=options.values;this.index=0;this._type=null;this._shuffled=null;this._direction=null;this.type=options.type};Tone.extend(Tone.CtrlPattern);Tone.CtrlPattern.Type={Up:"up",Down:"down",UpDown:"upDown",DownUp:"downUp",AlternateUp:"alternateUp",AlternateDown:"alternateDown",Random:"random",RandomWalk:"randomWalk",RandomOnce:"randomOnce",};Tone.CtrlPattern.defaults={"type":Tone.CtrlPattern.Type.Up,"values":[]};Object.defineProperty(Tone.CtrlPattern.prototype,"value",{get:function(){if(this.values.length===0){return}else if(this.values.length===1){return this.values[0]}
this.index=Math.min(this.index,this.values.length-1);var val=this.values[this.index];if(this.type===Tone.CtrlPattern.Type.RandomOnce){if(this.values.length!==this._shuffled.length){this._shuffleValues()}
val=this.values[this._shuffled[this.index]]}
return val}});Object.defineProperty(Tone.CtrlPattern.prototype,"type",{get:function(){return this._type},set:function(type){this._type=type;this._shuffled=null;if(this._type===Tone.CtrlPattern.Type.Up||this._type===Tone.CtrlPattern.Type.UpDown||this._type===Tone.CtrlPattern.Type.RandomOnce||this._type===Tone.CtrlPattern.Type.AlternateUp){this.index=0}else if(this._type===Tone.CtrlPattern.Type.Down||this._type===Tone.CtrlPattern.Type.DownUp||this._type===Tone.CtrlPattern.Type.AlternateDown){this.index=this.values.length-1}
if(this._type===Tone.CtrlPattern.Type.UpDown||this._type===Tone.CtrlPattern.Type.AlternateUp){this._direction=Tone.CtrlPattern.Type.Up}else if(this._type===Tone.CtrlPattern.Type.DownUp||this._type===Tone.CtrlPattern.Type.AlternateDown){this._direction=Tone.CtrlPattern.Type.Down}
if(this._type===Tone.CtrlPattern.Type.RandomOnce){this._shuffleValues()}else if(this._type===Tone.CtrlPattern.Random){this.index=Math.floor(Math.random()*this.values.length)}}});Tone.CtrlPattern.prototype.next=function(){var type=this.type;if(type===Tone.CtrlPattern.Type.Up){this.index++;if(this.index>=this.values.length){this.index=0}}else if(type===Tone.CtrlPattern.Type.Down){this.index--;if(this.index<0){this.index=this.values.length-1}}else if(type===Tone.CtrlPattern.Type.UpDown||type===Tone.CtrlPattern.Type.DownUp){if(this._direction===Tone.CtrlPattern.Type.Up){this.index++}else{this.index--}
if(this.index<0){this.index=1;this._direction=Tone.CtrlPattern.Type.Up}else if(this.index>=this.values.length){this.index=this.values.length-2;this._direction=Tone.CtrlPattern.Type.Down}}else if(type===Tone.CtrlPattern.Type.Random){this.index=Math.floor(Math.random()*this.values.length)}else if(type===Tone.CtrlPattern.Type.RandomWalk){if(Math.random()<0.5){this.index--;this.index=Math.max(this.index,0)}else{this.index++;this.index=Math.min(this.index,this.values.length-1)}}else if(type===Tone.CtrlPattern.Type.RandomOnce){this.index++;if(this.index>=this.values.length){this.index=0;this._shuffleValues()}}else if(type===Tone.CtrlPattern.Type.AlternateUp){if(this._direction===Tone.CtrlPattern.Type.Up){this.index+=2;this._direction=Tone.CtrlPattern.Type.Down}else{this.index-=1;this._direction=Tone.CtrlPattern.Type.Up}
if(this.index>=this.values.length){this.index=0;this._direction=Tone.CtrlPattern.Type.Up}}else if(type===Tone.CtrlPattern.Type.AlternateDown){if(this._direction===Tone.CtrlPattern.Type.Up){this.index+=1;this._direction=Tone.CtrlPattern.Type.Down}else{this.index-=2;this._direction=Tone.CtrlPattern.Type.Up}
if(this.index<0){this.index=this.values.length-1;this._direction=Tone.CtrlPattern.Type.Down}}
return this.value};Tone.CtrlPattern.prototype._shuffleValues=function(){var copy=[];this._shuffled=[];for(var i=0;i<this.values.length;i++){copy[i]=i}
while(copy.length>0){var randVal=copy.splice(Math.floor(copy.length*Math.random()),1);this._shuffled.push(randVal[0])}};Tone.CtrlPattern.prototype.dispose=function(){this._shuffled=null;this.values=null};return Tone.CtrlPattern})