define(["Tone/core/Tone","Tone/core/Type"],function(Tone){"use strict";Tone.IntervalTimeline=function(){this._root=null;this._length=0};Tone.extend(Tone.IntervalTimeline);Tone.IntervalTimeline.prototype.addEvent=function(event){if(this.isUndef(event.time)||this.isUndef(event.duration)){throw new Error("events must have time and duration parameters")}
var node=new IntervalNode(event.time,event.time+event.duration,event);if(this._root===null){this._root=node}else{this._root.insert(node)}
this._length++;while(node!==null){node.updateHeight();node.updateMax();this._rebalance(node);node=node.parent}
return this};Tone.IntervalTimeline.prototype.removeEvent=function(event){if(this._root!==null){var results=[];this._root.search(event.time,results);for(var i=0;i<results.length;i++){var node=results[i];if(node.event===event){this._removeNode(node);this._length--;break}}}
return this};Object.defineProperty(Tone.IntervalTimeline.prototype,"length",{get:function(){return this._length}});Tone.IntervalTimeline.prototype.cancel=function(after){after=this.toSeconds(after);this.forEachAfter(after,function(event){this.removeEvent(event)}.bind(this));return this};Tone.IntervalTimeline.prototype._setRoot=function(node){this._root=node;if(this._root!==null){this._root.parent=null}};Tone.IntervalTimeline.prototype._replaceNodeInParent=function(node,replacement){if(node.parent!==null){if(node.isLeftChild()){node.parent.left=replacement}else{node.parent.right=replacement}
this._rebalance(node.parent)}else{this._setRoot(replacement)}};Tone.IntervalTimeline.prototype._removeNode=function(node){if(node.left===null&&node.right===null){this._replaceNodeInParent(node,null)}else if(node.right===null){this._replaceNodeInParent(node,node.left)}else if(node.left===null){this._replaceNodeInParent(node,node.right)}else{var balance=node.getBalance();var replacement,temp;if(balance>0){if(node.left.right===null){replacement=node.left;replacement.right=node.right;temp=replacement}else{replacement=node.left.right;while(replacement.right!==null){replacement=replacement.right}
replacement.parent.right=replacement.left;temp=replacement.parent;replacement.left=node.left;replacement.right=node.right}}else{if(node.right.left===null){replacement=node.right;replacement.left=node.left;temp=replacement}else{replacement=node.right.left;while(replacement.left!==null){replacement=replacement.left}
replacement.parent=replacement.parent;replacement.parent.left=replacement.right;temp=replacement.parent;replacement.left=node.left;replacement.right=node.right}}
if(node.parent!==null){if(node.isLeftChild()){node.parent.left=replacement}else{node.parent.right=replacement}}else{this._setRoot(replacement)}
this._rebalance(temp)}
node.dispose()};Tone.IntervalTimeline.prototype._rotateLeft=function(node){var parent=node.parent;var isLeftChild=node.isLeftChild();var pivotNode=node.right;node.right=pivotNode.left;pivotNode.left=node;if(parent!==null){if(isLeftChild){parent.left=pivotNode}else{parent.right=pivotNode}}else{this._setRoot(pivotNode)}};Tone.IntervalTimeline.prototype._rotateRight=function(node){var parent=node.parent;var isLeftChild=node.isLeftChild();var pivotNode=node.left;node.left=pivotNode.right;pivotNode.right=node;if(parent!==null){if(isLeftChild){parent.left=pivotNode}else{parent.right=pivotNode}}else{this._setRoot(pivotNode)}};Tone.IntervalTimeline.prototype._rebalance=function(node){var balance=node.getBalance();if(balance>1){if(node.left.getBalance()<0){this._rotateLeft(node.left)}else{this._rotateRight(node)}}else if(balance<-1){if(node.right.getBalance()>0){this._rotateRight(node.right)}else{this._rotateLeft(node)}}};Tone.IntervalTimeline.prototype.getEvent=function(time){if(this._root!==null){var results=[];this._root.search(time,results);if(results.length>0){var max=results[0];for(var i=1;i<results.length;i++){if(results[i].low>max.low){max=results[i]}}
return max.event}}
return null};Tone.IntervalTimeline.prototype.forEach=function(callback){if(this._root!==null){var allNodes=[];if(this._root!==null){this._root.traverse(function(node){allNodes.push(node)})}
for(var i=0;i<allNodes.length;i++){var ev=allNodes[i].event;if(ev){callback(ev)}}}
return this};Tone.IntervalTimeline.prototype.forEachOverlap=function(time,callback){time=this.toSeconds(time);if(this._root!==null){var results=[];this._root.search(time,results);for(var i=results.length-1;i>=0;i--){var ev=results[i].event;if(ev){callback(ev)}}}
return this};Tone.IntervalTimeline.prototype.forEachAfter=function(time,callback){time=this.toSeconds(time);if(this._root!==null){var results=[];this._root.searchAfter(time,results);for(var i=results.length-1;i>=0;i--){var ev=results[i].event;if(ev){callback(ev)}}}
return this};Tone.IntervalTimeline.prototype.dispose=function(){var allNodes=[];if(this._root!==null){this._root.traverse(function(node){allNodes.push(node)})}
for(var i=0;i<allNodes.length;i++){allNodes[i].dispose()}
allNodes=null;this._root=null;return this};var IntervalNode=function(low,high,event){this.event=event;this.low=low;this.high=high;this.max=this.high;this._left=null;this._right=null;this.parent=null;this.height=0};IntervalNode.prototype.insert=function(node){if(node.low<=this.low){if(this.left===null){this.left=node}else{this.left.insert(node)}}else{if(this.right===null){this.right=node}else{this.right.insert(node)}}};IntervalNode.prototype.search=function(point,results){if(point>this.max){return}
if(this.left!==null){this.left.search(point,results)}
if(this.low<=point&&this.high>=point){results.push(this)}
if(this.low>point){return}
if(this.right!==null){this.right.search(point,results)}};IntervalNode.prototype.searchAfter=function(point,results){if(this.low>=point){results.push(this);if(this.left!==null){this.left.searchAfter(point,results)}}
if(this.right!==null){this.right.searchAfter(point,results)}};IntervalNode.prototype.traverse=function(callback){callback(this);if(this.left!==null){this.left.traverse(callback)}
if(this.right!==null){this.right.traverse(callback)}};IntervalNode.prototype.updateHeight=function(){if(this.left!==null&&this.right!==null){this.height=Math.max(this.left.height,this.right.height)+1}else if(this.right!==null){this.height=this.right.height+1}else if(this.left!==null){this.height=this.left.height+1}else{this.height=0}};IntervalNode.prototype.updateMax=function(){this.max=this.high;if(this.left!==null){this.max=Math.max(this.max,this.left.max)}
if(this.right!==null){this.max=Math.max(this.max,this.right.max)}};IntervalNode.prototype.getBalance=function(){var balance=0;if(this.left!==null&&this.right!==null){balance=this.left.height-this.right.height}else if(this.left!==null){balance=this.left.height+1}else if(this.right!==null){balance=-(this.right.height+1)}
return balance};IntervalNode.prototype.isLeftChild=function(){return this.parent!==null&&this.parent.left===this};Object.defineProperty(IntervalNode.prototype,"left",{get:function(){return this._left},set:function(node){this._left=node;if(node!==null){node.parent=this}
this.updateHeight();this.updateMax()}});Object.defineProperty(IntervalNode.prototype,"right",{get:function(){return this._right},set:function(node){this._right=node;if(node!==null){node.parent=this}
this.updateHeight();this.updateMax()}});IntervalNode.prototype.dispose=function(){this.parent=null;this._left=null;this._right=null;this.event=null};return Tone.IntervalTimeline})